// swift-tools-version: 6.2
import PackageDescription

let package = Package(
    name: "Tether",
    platforms: [.iOS(.v26), .macOS(.v26)],
    products: [
        .library(name: "Tether", targets: ["Tether"]),
    ],
    targets: [
        // The Rust core, prebuilt. A consumer needs no Rust toolchain, no
        // CMake and no build plugin.
        .binaryTarget(name: "TetherFFI", path: "Artifacts/TetherFFI.xcframework"),

        // Generated by uniffi and checked in verbatim; never hand-edited, and
        // never imported by a consumer. Swift 5 language mode because the
        // generator does not emit Swift 6 strict-concurrency-clean code.
        .target(
            name: "TetherFFIBindings",
            dependencies: ["TetherFFI"],
            swiftSettings: [.swiftLanguageMode(.v5)]
        ),

        // The surface consumers see: Swift 6, no generated symbols.
        .target(name: "Tether", dependencies: ["TetherFFIBindings"]),

        .testTarget(name: "TetherTests", dependencies: ["Tether"]),
    ]
)
