import Foundation

/// Explicit export only. Never gives an external SSH client a Keychain private key
/// or claims that Tether's confirmation policy is enforced by system OpenSSH.
struct OpenSSHExport {
  static func render(_ hosts: [Host], existing: SSHConfig) throws -> String {
    var aliases: Set<String> = []
    var result = "# Generated by Tether. Edit managed hosts in Tether.\n"
    for host in hosts where host.isManaged {
      guard let p = host.profile, p.authentication.confirmation == .automatic,
        p.authentication.otp == nil, p.authentication.remoteApprovalDevice == nil,
        host.connectionProblem == nil else { continue }
      let alias = host.sshTarget
      guard !alias.isEmpty, alias.allSatisfy({ $0.isLetter || $0.isNumber || "-_.".contains($0) }),
        aliases.insert(alias.lowercased()).inserted,
        !existing.entries.contains(where: { $0.alias.lowercased() == alias.lowercased() }) else {
        throw IdentityError.storage("Resolve the SSH alias conflict for \(alias) before exporting.")
      }
      guard host.credentialSecretID == nil else {
        throw IdentityError.storage("\(alias) uses a device-bound key that system SSH cannot read.")
      }
      try p.validate()
      result += "Host \(alias)\n  HostName \(p.hostname)\n  User \(p.username)\n  Port \(p.port)\n"
      if let path = host.keyPath {
        guard !path.contains(where: \.isNewline), !path.contains("%"), !path.contains("${") else { throw IdentityError.invalidConfiguration }
        result += "  IdentityFile \"\(path.replacingOccurrences(of: "\\", with: "\\\\").replacingOccurrences(of: "\"", with: "\\\""))\"\n  IdentitiesOnly yes\n"
      }
      result += "\n"
    }
    return result
  }
}

extension HostStore {
  func exportOpenSSH() {
    #if os(macOS)
    do {
      let path = Self.sshConfig
      let existing = FileManager.default.fileExists(atPath: path.path)
        ? try String(contentsOf: path, encoding: .utf8) : ""
      let rendered = try OpenSSHExport.render(hosts, existing: SSHConfig(existing))
      let target = path.deletingLastPathComponent().appending(path: "tether_config")
      let receipt = target.appendingPathExtension("last-export")
      if FileManager.default.fileExists(atPath: target.path) {
        guard let previous = try? Data(contentsOf: receipt), try Data(contentsOf: target) == previous else {
          throw IdentityError.storage("The generated SSH file was edited externally. Preserve or import those edits before exporting again.")
        }
      }
      let data = Data(rendered.utf8)
      try FileManager.default.createDirectory(at: target.deletingLastPathComponent(), withIntermediateDirectories: true, attributes: [.posixPermissions: 0o700])
      try data.write(to: target, options: .atomic)
      try FileManager.default.setAttributes([.posixPermissions: 0o600], ofItemAtPath: target.path)
      try data.write(to: receipt, options: .atomic)
      // An absolute quoted Include avoids assuming ssh's working directory.
      let include = "Include \"\(target.path)\""
      if !existing.components(separatedBy: .newlines).contains(include) {
        try (include + "\n" + existing).write(to: path, atomically: true, encoding: .utf8)
        try FileManager.default.setAttributes([.posixPermissions: 0o600], ofItemAtPath: path.path)
      }
    } catch { recordProblem(error) }
    #endif
  }
}
